### PR TITLE
Feature/namespace js

### PR DESCRIPTION
**Pull request by brandonneil**
Namespaced the javascript settings to Drupal.settings.sitenowMaps to minimize the potential for namespace collisions.

### CODE REVIEW

**Comment by genjohnson** [comment]
I did a visual check and this all looks fine to me, but I have not tested this on a site.

**Comment by brandonneil** [comment]
😭

**Comment by richardbporter** [comment]
FYI - @brandonneil I changed the base branch for this PR (which I didn't realize you could do) and then resolved conflicts.

**Comment by brandonneil** [comment]
Nice

**Comment by richardbporter** [comment]
I tested each setting out locally and they all worked as expected. I didn't have any issues with caching either. I think this is good to go.

**Pull request merged**
