### PR TITLE
Bug/default value when editing

### PR DESCRIPTION
**Pull request by genjohnson**
When editing a node, the default field value was being set to NULL (forcing editors to re-select a building every time a node was edited). This now checks if the field already has a value saved and will use that value, and if not will use the default value configured in the field instance settings.

### CODE REVIEW

**Comment by richardbporter** [comment]
I'm not going to have time to test this before I leave.

**Comment by brandonneil** [comment]
Is the hope that this gets added to the current update cycle? If so, I'll make some time to review it this week.

**Comment by genjohnson** [comment]
Ideally this would get added during the current update cycle, but I’ve already patched the module local to the site I’m working on, so it can wait a month if necessary.

- Genevieve

**Comment by brandonneil** [comment]
Works well, thanks!

**Pull request merged**
